// fix-agent.ts — Agent SDK-powered fix agent that rewrites Postgres queries to ES
//
// Uses the Claude Agent SDK to autonomously:
//   1. Read flagged source files
//   2. Inspect ES cluster via Preflex MCP server
//   3. Rewrite queries to use @elastic/elasticsearch
//   4. Create a fix PR via `gh`

import { query } from "@anthropic-ai/claude-agent-sdk";
import { FIX_PROMPT } from "./prompts.js";

export interface FixAgentOptions {
  mcpBaseUrl: string;
  elasticMcpUrl: string;
  repoRoot: string;
  reviewSummary: string;
  prNumber: number;
  baseBranch: string;
  maxTurns?: number;
}

export interface FixAgentResult {
  fixPrUrl: string | null;
  result: string;
  turns: number;
  costUsd: number;
}

/**
 * Run the fix agent using the Claude Agent SDK.
 *
 * The agent gets:
 * - Built-in tools: Read, Write, Edit, Bash (for gh), Glob, Grep
 * - Preflex MCP server: ES cluster inspection tools
 * - System prompt: how to rewrite queries
 * - User prompt: the specific findings to fix
 */
export async function runFixAgent(opts: FixAgentOptions): Promise<FixAgentResult> {
  const {
    mcpBaseUrl,
    elasticMcpUrl,
    repoRoot,
    reviewSummary,
    prNumber,
    baseBranch,
    maxTurns = 15,
  } = opts;

  const prompt = [
    "Here are the Preflex review findings — queries that need to be rewritten from Postgres to Elasticsearch:\n",
    reviewSummary,
    "\n\nYour task:",
    `1. Read the flagged source files in ${repoRoot}`,
    "2. Inspect the ES cluster via MCP tools (use elasticsearch tools like get_mappings, list_indices, search to understand available indices and field types)",
    "3. Rewrite each flagged query to use the @elastic/elasticsearch client",
    "4. Preserve all Postgres write operations (INSERT/UPDATE/DELETE)",
    "5. Update or create src/es.ts with the ES client if needed",
    `6. Create a new git branch 'preflex/fix-${prNumber}' from '${baseBranch}'`,
    "7. Commit all changes with message: 'refactor: migrate search queries to Elasticsearch'",
    `8. Push the branch and create a PR targeting '${baseBranch}' using: gh pr create --title "refactor: migrate search queries to Elasticsearch" --body "Rewrites Postgres search queries to use Elasticsearch.\\n\\nGenerated by Preflex."`,
    "\nAfter creating the PR, output the PR URL on the last line of your response, prefixed with 'PR_URL: '",
  ].join("\n");

  let fixPrUrl: string | null = null;
  let resultText = "";
  let turns = 0;
  let costUsd = 0;

  for await (const message of query({
    prompt,
    options: {
      systemPrompt: FIX_PROMPT,
      allowedTools: [
        "Read",
        "Write",
        "Edit",
        "Bash",
        "Glob",
        "Grep",
        "mcp__preflex__*",
        "mcp__elasticsearch__*",
      ],
      permissionMode: "bypassPermissions",
      allowDangerouslySkipPermissions: true,
      maxTurns,
      model: "claude-sonnet-4-5-20250929",
      cwd: repoRoot,
      mcpServers: {
        preflex: {
          type: "http",
          url: `${mcpBaseUrl}/mcp`,
        },
        elasticsearch: {
          type: "http",
          url: `${elasticMcpUrl}/mcp`,
        },
      },
    },
  })) {
    if (message.type === "system" && message.subtype === "init") {
      console.log(`Fix agent session: ${message.session_id}`);
      const failed = message.mcp_servers.filter((s: { status: string }) => s.status !== "connected");
      if (failed.length > 0) {
        console.warn("MCP server connection issues:", failed);
      }
    }

    if (message.type === "result") {
      if (message.subtype === "success") {
        resultText = message.result;
        turns = message.num_turns;
        costUsd = message.total_cost_usd;

        // Extract PR URL from the result
        const prUrlMatch = resultText.match(/PR_URL:\s*(https:\/\/github\.com\/\S+)/);
        if (prUrlMatch) {
          fixPrUrl = prUrlMatch[1];
        }
        // Also try to find any github PR URL in the output
        if (!fixPrUrl) {
          const ghUrlMatch = resultText.match(/https:\/\/github\.com\/[^\s]+\/pull\/\d+/);
          if (ghUrlMatch) {
            fixPrUrl = ghUrlMatch[0];
          }
        }
      } else {
        console.error("Fix agent failed:", message.subtype);
        if ("errors" in message) {
          console.error("Errors:", message.errors);
        }
      }
    }
  }

  console.log(`Fix agent completed in ${turns} turns ($${costUsd.toFixed(3)})`);
  if (fixPrUrl) {
    console.log(`Fix PR: ${fixPrUrl}`);
  }

  return { fixPrUrl, result: resultText, turns, costUsd };
}

// ── Main entry point (standalone mode) ──────────────────────────────────────

async function main(): Promise<void> {
  const prNumber = parseInt(process.env.PR_NUMBER ?? "", 10);
  const mcpBaseUrl = process.env.MCP_BASE_URL ?? "http://127.0.0.1:3100";
  const elasticMcpUrl = process.env.ELASTIC_MCP_URL ?? "http://127.0.0.1:8080";
  const repoRoot = process.env.GITHUB_WORKSPACE ?? process.cwd();
  const baseBranch = process.env.BASE_BRANCH ?? "main";

  if (!prNumber) {
    console.error("Missing PR_NUMBER");
    process.exit(1);
  }

  const reviewSummary = process.env.REVIEW_SUMMARY ?? "No findings provided — inspect the PR diff and identify queries to migrate.";

  const result = await runFixAgent({
    mcpBaseUrl,
    elasticMcpUrl,
    repoRoot,
    reviewSummary,
    prNumber,
    baseBranch,
  });

  if (result.fixPrUrl) {
    console.log(`\nFix PR created: ${result.fixPrUrl}`);
  } else {
    console.log("\nNo fix PR was created.");
  }
}

const isMain =
  import.meta.url === `file://${process.argv[1]}` ||
  process.argv[1]?.endsWith("/fix-agent.js");

if (isMain) {
  main().catch((err) => {
    console.error("Fix agent failed:", err);
    process.exit(1);
  });
}
